name: Tests CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build imagedev
      run: make imagedev
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run check
      run: make check
    
    - name: Run static check
      run: make static-analysis
